### PR TITLE
Updates/aliased attributes

### PR DESCRIPTION
**Pull request by TBNolan**
- Adds documentation about aliased attributes `sonarr_add_missing` and `radarr_add_missing`
- Fixes `radarr_add_existing` / `sonarr_add_existing` section

### CODE REVIEW

**Comment by meisnate12** [comment]
so the fixes are great but i don't usually highlight alias. the only reason the alias is there is so old configs still work i don't want to advertise their usage if possible.

**Comment by TBNolan** [comment]
Sounds good, no problem!

I just noticed a new warning in my logs, so I figured I would try to document it: 
```Collection Warning: radarr_add attribute will run as radarr_add_missing```

Thanks for the great software, looking forward to contributing in the future

**Comment by meisnate12** [comment]
theres quite a few old attributes that would make my already confusing wiki every worse haha

**Comment by meisnate12** [comment]
Also check out the discord to chat with us about features and other pmm nonsense!

**Pull request merged**
